name: report-test-results
description: Report test results.
inputs:
  path:
    description: Glob pattern for the JUnit report files.
    required: true
  github_token:
    description: GitHub access token.
    required: false
runs:
  using: composite
  steps:
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - run: deno run --allow-all src/main.ts
      env:
        GITHUB_TOKEN: ${{ inputs.github_token || github.token }}
        REPORT_TEST_RESULTS_INPUTS_PATH: ${{ inputs.path }}
      shell: bash
branding:
  color: blue
  icon: file-text
